# -*- coding: utf-8 -*-
"""GEERailways.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTodRDtspd-Naz9dBvXIxGZ1s5vP2rf-
"""

import geemap,geemap as import_map

import ee

ee.Authenticate()

ee.Initialize(project='rohitshinde4680')

map=import_map.Map()

vector_layer = ee.FeatureCollection("projects/ee-rohitshinde090103/assets/railways")

Map = geemap.Map()

Map.addLayer(vector_layer, {}, 'railways kolkata')

Map