# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ocdn6zckCgvUAuf86gpbV3yi4jMpe3mO
"""

import geemap,geemap as import_map

import ee

ee.Authenticate()

ee.Initialize(project='rohitshinde4680')

vis_map=import_map.Map()

studyarea=ee.FeatureCollection('projects/ee-rohitshinde090103/assets/Kolkata_boundary') #defining my study area

sentinel_data_2016=ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2016-06-01', '2016-12-31')
sentinel_data_2024=ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2024-06-01', '2024-12-31')

sentinel_2016_tcc=sentinel_data_2016.select('B4','B3','B2').mean().clip(studyarea)
sentinel_2016_fcc=sentinel_data_2016.select('B8','B4','B3').mean().clip(studyarea)

sentinel_2024_tcc=sentinel_data_2024.select('B4','B3','B2').mean().clip(studyarea)
sentinel_2024_fcc=sentinel_data_2024.select('B8','B4','B3').mean().clip(studyarea)



vis_map.addLayer(sentinel_2016_tcc,{},'TCC_2016')
vis_map.addLayer(sentinel_2016_fcc,{},'FCC_2016')
vis_map.addLayer(sentinel_2024_tcc,{},'TCC_2024')
vis_map.addLayer(sentinel_2024_fcc,{},'FCC_2024')

vis_map.center_object(studyarea,9)
vis_map